# Generated by Django 5.1.4 on 2025-01-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=80)),
                ('address', models.TextField()),
                ('drpCountry', models.CharField(max_length=15)),
                ('drpState', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Register',
            },
        ),
    ]
