# Generated by Django 5.1.4 on 2025-01-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_register_drpstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='drpCountry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='drpState',
            new_name='state',
        ),
    ]
