# Generated by Django 5.1.4 on 2025-01-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_drpcountry_register_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_photos/'),
        ),
    ]
