# Generated by Django 5.1.4 on 2025-01-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_register_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
