# Generated by Django 5.1.4 on 2025-01-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
    ]
