# Generated by Django 5.1.4 on 2025-01-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_register_email_alter_register_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
